package olbs.be.model.entities;
// Generated 02-Apr-2019, 9:52:11 PM by Hibernate Tools 5.2.12.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "configuration")
public class Configuration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String parameter;
	private String value;

	public Configuration() {
	}

	public Configuration(String parameter) {
		this.parameter = parameter;
	}

	public Configuration(String parameter, String value) {
		this.parameter = parameter;
		this.value = value;
	}

	@Id

	@Column(name = "parameter", unique = true, nullable = false, length = 50)
	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
