package olbs.be.model.entities;
// Generated 16-Mar-2019, 8:54:16 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FeeStructure generated by hbm2java
 */
@Entity
@Table(name = "fee_structure", catalog = "olbs")
public class FeeStructure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String standard;
	private Integer tuitionFee;
	private Integer annualFee;
	private Integer examinationFee;
	private Integer courseFee;

	public FeeStructure() {
	}

	public FeeStructure(String standard) {
		this.standard = standard;
	}

	public FeeStructure(String standard, Integer tuitionFee, Integer annualFee, Integer examinationFee,
			Integer courseFee) {
		this.standard = standard;
		this.tuitionFee = tuitionFee;
		this.annualFee = annualFee;
		this.examinationFee = examinationFee;
		this.courseFee = courseFee;
	}

	@Id

	@Column(name = "standard", unique = true, nullable = false, length = 50)
	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	@Column(name = "tuition_fee")
	public Integer getTuitionFee() {
		return this.tuitionFee;
	}

	public void setTuitionFee(Integer tuitionFee) {
		this.tuitionFee = tuitionFee;
	}

	@Column(name = "annual_fee")
	public Integer getAnnualFee() {
		return this.annualFee;
	}

	public void setAnnualFee(Integer annualFee) {
		this.annualFee = annualFee;
	}

	@Column(name = "examination_fee")
	public Integer getExaminationFee() {
		return this.examinationFee;
	}

	public void setExaminationFee(Integer examinationFee) {
		this.examinationFee = examinationFee;
	}

	@Column(name = "course_fee")
	public Integer getCourseFee() {
		return this.courseFee;
	}

	public void setCourseFee(Integer courseFee) {
		this.courseFee = courseFee;
	}

}
