package olbs.be.model.entities;
// Generated 13-Apr-2019, 9:07:50 PM by Hibernate Tools 5.2.12.Final

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventImagesId generated by hbm2java
 */
@Embeddable
public class EventImagesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String eventName;
	private LocalDate eventDate;

	public EventImagesId() {
	}

	public EventImagesId(String eventName, LocalDate eventDate) {
		this.eventName = eventName;
		this.eventDate = eventDate;
	}

	@Column(name = "event_name", nullable = false, length = 50)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "event_date", nullable = false, length = 0)
	public LocalDate getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(LocalDate eventDate) {
		this.eventDate = eventDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventImagesId))
			return false;
		EventImagesId castOther = (EventImagesId) other;

		return ((this.getEventName() == castOther.getEventName()) || (this.getEventName() != null
				&& castOther.getEventName() != null && this.getEventName().equals(castOther.getEventName())))
				&& ((this.getEventDate() == castOther.getEventDate()) || (this.getEventDate() != null
						&& castOther.getEventDate() != null && this.getEventDate().equals(castOther.getEventDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventName() == null ? 0 : this.getEventName().hashCode());
		result = 37 * result + (getEventDate() == null ? 0 : this.getEventDate().hashCode());
		return result;
	}

}
